-- Add-on engine fields for investment_universe
-- Run with: psql $DATABASE_URL -f supabase/patches/012_investment_universe_addons.sql

ALTER TABLE public.investment_universe
  ADD COLUMN IF NOT EXISTS addon_summary text,
  ADD COLUMN IF NOT EXISTS addon_flags jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_addon_run_at timestamptz;

COMMENT ON COLUMN public.investment_universe.addon_summary
  IS 'Latest summary generated by the ValueBot add-on engine (Module 7).';
COMMENT ON COLUMN public.investment_universe.addon_flags
  IS 'JSON flag bundle generated by Module 7 add-ons (debt, liquidity, dividend risk, fraud, etc.).';
COMMENT ON COLUMN public.investment_universe.last_addon_run_at
  IS 'Timestamp of the last Module 7 add-on execution for this row.';
