/**
 * Achievement Definitions
 * 80+ achievements across multiple categories
 */

import { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  // ========== DICE & ROLLING (10 achievements) ==========
  {
    id: 'first_roll',
    category: 'dice',
    title: 'First Roll',
    description: 'Roll the dice for the first time',
    icon: '🎲',
    reward: 10,
    requirement: { type: 'count', metric: 'totalRolls', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'century_club',
    category: 'dice',
    title: 'Century Club',
    description: 'Roll the dice 100 times',
    icon: '🎲',
    reward: 100,
    requirement: { type: 'count', metric: 'totalRolls', target: 100 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'roll_master',
    category: 'dice',
    title: 'Roll Master',
    description: 'Roll the dice 1000 times',
    icon: '🎲',
    reward: 500,
    requirement: { type: 'count', metric: 'totalRolls', target: 1000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'roll_legend',
    category: 'dice',
    title: 'Roll Legend',
    description: 'Roll the dice 5000 times',
    icon: '🎲',
    reward: 2000,
    requirement: { type: 'count', metric: 'totalRolls', target: 5000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'lucky_streak',
    category: 'dice',
    title: 'Lucky Streak',
    description: 'Roll a 6 five times in a row',
    icon: '🍀',
    reward: 200,
    requirement: { type: 'streak', metric: 'roll6Streak', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'super_lucky',
    category: 'dice',
    title: 'Super Lucky',
    description: 'Roll a 6 ten times in a row',
    icon: '🍀',
    reward: 1000,
    requirement: { type: 'streak', metric: 'roll6Streak', target: 10 },
    isHidden: false,
    isSecret: true,
  },
  {
    id: 'daily_roller',
    category: 'dice',
    title: 'Daily Roller',
    description: 'Use all daily rolls in one day',
    icon: '⚡',
    reward: 50,
    requirement: { type: 'custom', metric: 'use_all_daily_rolls', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'persistent_roller',
    category: 'dice',
    title: 'Persistent Roller',
    description: 'Use all daily rolls for 7 days straight',
    icon: '⚡',
    reward: 300,
    requirement: { type: 'streak', metric: 'daily_all_rolls', target: 7 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'snake_eyes',
    category: 'dice',
    title: 'Snake Eyes',
    description: 'Roll a 1 three times in a row',
    icon: '🐍',
    reward: 75,
    requirement: { type: 'streak', metric: 'roll1Streak', target: 3 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'balanced_roller',
    category: 'dice',
    title: 'Balanced Roller',
    description: 'Roll each number (1-6) at least 50 times',
    icon: '⚖️',
    reward: 250,
    requirement: { type: 'custom', metric: 'balanced_rolls', target: 1 },
    isHidden: false,
    isSecret: false,
  },

  // ========== INVESTING (15 achievements) ==========
  {
    id: 'first_investment',
    category: 'investing',
    title: 'First Investment',
    description: 'Buy your first stock',
    icon: '💰',
    reward: 25,
    requirement: { type: 'count', metric: 'stocksPurchased', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'active_trader',
    category: 'investing',
    title: 'Active Trader',
    description: 'Buy 50 stocks',
    icon: '💰',
    reward: 100,
    requirement: { type: 'count', metric: 'stocksPurchased', target: 50 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'portfolio_starter',
    category: 'investing',
    title: 'Portfolio Starter',
    description: 'Own 10 different stocks',
    icon: '📊',
    reward: 100,
    requirement: { type: 'count', metric: 'uniqueStocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'diversified_investor',
    category: 'investing',
    title: 'Diversified Investor',
    description: 'Own stocks from all 5 categories',
    icon: '🌐',
    reward: 150,
    requirement: { type: 'collection', metric: 'all_categories', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'thousandaire',
    category: 'investing',
    title: 'Thousandaire',
    description: 'Reach $100k net worth',
    icon: '💵',
    reward: 50,
    requirement: { type: 'threshold', metric: 'netWorth', target: 100000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'half_millionaire',
    category: 'investing',
    title: 'Half Millionaire',
    description: 'Reach $500k net worth',
    icon: '💵',
    reward: 250,
    requirement: { type: 'threshold', metric: 'netWorth', target: 500000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'millionaire',
    category: 'investing',
    title: 'Millionaire',
    description: 'Reach $1M net worth',
    icon: '💵',
    reward: 500,
    requirement: { type: 'threshold', metric: 'netWorth', target: 1000000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'multi_millionaire',
    category: 'investing',
    title: 'Multi-Millionaire',
    description: 'Reach $10M net worth',
    icon: '💎',
    reward: 1000,
    requirement: { type: 'threshold', metric: 'netWorth', target: 10000000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'decamillionaire',
    category: 'investing',
    title: 'Decamillionaire',
    description: 'Reach $50M net worth',
    icon: '💎',
    reward: 2500,
    requirement: { type: 'threshold', metric: 'netWorth', target: 50000000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'billionaire',
    category: 'investing',
    title: 'Billionaire',
    description: 'Reach $1B net worth',
    icon: '👑',
    reward: 5000,
    requirement: { type: 'threshold', metric: 'netWorth', target: 1000000000 },
    isHidden: false,
    isSecret: true,
  },
  {
    id: 'value_investor',
    category: 'investing',
    title: 'Value Investor',
    description: 'Own 10 value stocks',
    icon: '📈',
    reward: 100,
    requirement: { type: 'custom', metric: 'value_stocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'growth_hunter',
    category: 'investing',
    title: 'Growth Hunter',
    description: 'Own 10 growth stocks',
    icon: '🚀',
    reward: 100,
    requirement: { type: 'custom', metric: 'growth_stocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'dividend_collector',
    category: 'investing',
    title: 'Dividend Collector',
    description: 'Own 10 dividend stocks',
    icon: '💵',
    reward: 100,
    requirement: { type: 'custom', metric: 'dividend_stocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'moat_master',
    category: 'investing',
    title: 'Moat Master',
    description: 'Own 10 moat stocks',
    icon: '🏰',
    reward: 100,
    requirement: { type: 'custom', metric: 'moat_stocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'turnaround_specialist',
    category: 'investing',
    title: 'Turnaround Specialist',
    description: 'Own 10 turnaround stocks',
    icon: '🔄',
    reward: 100,
    requirement: { type: 'custom', metric: 'turnaround_stocks', target: 10 },
    isHidden: false,
    isSecret: false,
  },

  // ========== STARS (8 achievements) ==========
  {
    id: 'star_gazer',
    category: 'stars',
    title: 'Star Gazer',
    description: 'Earn your first star',
    icon: '⭐',
    reward: 10,
    requirement: { type: 'count', metric: 'totalStarsEarned', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_hunter',
    category: 'stars',
    title: 'Star Hunter',
    description: 'Earn 100 stars',
    icon: '⭐',
    reward: 50,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 100 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_collector',
    category: 'stars',
    title: 'Star Collector',
    description: 'Earn 1000 stars',
    icon: '🌟',
    reward: 100,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 1000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_master',
    category: 'stars',
    title: 'Star Master',
    description: 'Earn 5000 stars',
    icon: '🌟',
    reward: 500,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 5000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_legend',
    category: 'stars',
    title: 'Star Legend',
    description: 'Earn 10000 stars',
    icon: '✨',
    reward: 1000,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 10000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_constellation',
    category: 'stars',
    title: 'Star Constellation',
    description: 'Earn 25000 stars',
    icon: '✨',
    reward: 2500,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 25000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_galaxy',
    category: 'stars',
    title: 'Star Galaxy',
    description: 'Earn 50000 stars',
    icon: '🌌',
    reward: 5000,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 50000 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'star_universe',
    category: 'stars',
    title: 'Star Universe',
    description: 'Earn 100000 stars',
    icon: '🌌',
    reward: 10000,
    requirement: { type: 'threshold', metric: 'totalStarsEarned', target: 100000 },
    isHidden: false,
    isSecret: true,
  },

  // ========== QUIZ & LEARNING (10 achievements) ==========
  {
    id: 'first_lesson',
    category: 'quiz',
    title: 'First Lesson',
    description: 'Complete your first Bias Sanctuary quiz',
    icon: '🧠',
    reward: 50,
    requirement: { type: 'count', metric: 'quizzesCompleted', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'student',
    category: 'quiz',
    title: 'Student',
    description: 'Complete 10 quizzes',
    icon: '🧠',
    reward: 100,
    requirement: { type: 'count', metric: 'quizzesCompleted', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'scholar',
    category: 'quiz',
    title: 'Scholar',
    description: 'Complete 50 quizzes',
    icon: '🎓',
    reward: 500,
    requirement: { type: 'count', metric: 'quizzesCompleted', target: 50 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'professor',
    category: 'quiz',
    title: 'Professor',
    description: 'Complete 100 quizzes',
    icon: '🎓',
    reward: 1000,
    requirement: { type: 'count', metric: 'quizzesCompleted', target: 100 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'perfect_student',
    category: 'quiz',
    title: 'Perfect Student',
    description: 'Get 100% on 5 quizzes',
    icon: '🎓',
    reward: 250,
    requirement: { type: 'count', metric: 'perfectQuizzes', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'ace',
    category: 'quiz',
    title: 'Ace',
    description: 'Get 100% on 20 quizzes',
    icon: '💯',
    reward: 750,
    requirement: { type: 'count', metric: 'perfectQuizzes', target: 20 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'genius',
    category: 'quiz',
    title: 'Genius',
    description: 'Get 100% on 50 quizzes',
    icon: '💯',
    reward: 2000,
    requirement: { type: 'count', metric: 'perfectQuizzes', target: 50 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'bias_buster',
    category: 'quiz',
    title: 'Bias Buster',
    description: 'Complete a quiz on every bias type',
    icon: '🧠',
    reward: 300,
    requirement: { type: 'custom', metric: 'all_bias_types', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'quick_learner',
    category: 'quiz',
    title: 'Quick Learner',
    description: 'Complete 5 quizzes in one day',
    icon: '⚡',
    reward: 150,
    requirement: { type: 'custom', metric: 'quizzes_in_day', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'dedicated_learner',
    category: 'quiz',
    title: 'Dedicated Learner',
    description: 'Complete at least one quiz every day for 7 days',
    icon: '📚',
    reward: 400,
    requirement: { type: 'streak', metric: 'daily_quiz', target: 7 },
    isHidden: false,
    isSecret: false,
  },

  // ========== CASINO (10 achievements) ==========
  {
    id: 'first_gamble',
    category: 'casino',
    title: 'First Gamble',
    description: 'Play your first scratchcard',
    icon: '🎰',
    reward: 25,
    requirement: { type: 'count', metric: 'scratchcardsPlayed', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'casual_gambler',
    category: 'casino',
    title: 'Casual Gambler',
    description: 'Play 50 scratchcards',
    icon: '🎰',
    reward: 100,
    requirement: { type: 'count', metric: 'scratchcardsPlayed', target: 50 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'high_roller',
    category: 'casino',
    title: 'High Roller',
    description: 'Play 200 scratchcards',
    icon: '🎰',
    reward: 400,
    requirement: { type: 'count', metric: 'scratchcardsPlayed', target: 200 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'lucky_winner',
    category: 'casino',
    title: 'Lucky Winner',
    description: 'Win 1 scratchcard',
    icon: '🍀',
    reward: 50,
    requirement: { type: 'count', metric: 'scratchcardsWon', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'frequent_winner',
    category: 'casino',
    title: 'Frequent Winner',
    description: 'Win 25 scratchcards',
    icon: '🍀',
    reward: 250,
    requirement: { type: 'count', metric: 'scratchcardsWon', target: 25 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'jackpot_hunter',
    category: 'casino',
    title: 'Jackpot Hunter',
    description: 'Win 100 scratchcards',
    icon: '💰',
    reward: 1000,
    requirement: { type: 'count', metric: 'scratchcardsWon', target: 100 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'hot_streak',
    category: 'casino',
    title: 'Hot Streak',
    description: 'Win 5 scratchcards in a row',
    icon: '🔥',
    reward: 300,
    requirement: { type: 'streak', metric: 'scratchcardWinStreak', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'burning_hot',
    category: 'casino',
    title: 'Burning Hot',
    description: 'Win 10 scratchcards in a row',
    icon: '🔥',
    reward: 1000,
    requirement: { type: 'streak', metric: 'scratchcardWinStreak', target: 10 },
    isHidden: false,
    isSecret: true,
  },
  {
    id: 'lady_luck',
    category: 'casino',
    title: 'Lady Luck',
    description: 'Win 3 scratchcards in your first 5 plays',
    icon: '🍀',
    reward: 200,
    requirement: { type: 'custom', metric: 'early_wins', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'knows_when_to_stop',
    category: 'casino',
    title: 'Knows When to Stop',
    description: 'Win and then stop playing for the day',
    icon: '🛑',
    reward: 150,
    requirement: { type: 'custom', metric: 'win_and_stop', target: 1 },
    isHidden: false,
    isSecret: false,
  },

  // ========== EXPLORATION (8 achievements) ==========
  {
    id: 'first_steps',
    category: 'exploration',
    title: 'First Steps',
    description: 'Visit 5 different tiles',
    icon: '👣',
    reward: 25,
    requirement: { type: 'custom', metric: 'unique_tiles', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'explorer',
    category: 'exploration',
    title: 'Explorer',
    description: 'Visit 15 different tiles',
    icon: '🗺️',
    reward: 75,
    requirement: { type: 'custom', metric: 'unique_tiles', target: 15 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'world_traveler',
    category: 'exploration',
    title: 'World Traveler',
    description: 'Land on all 26 tiles',
    icon: '🌍',
    reward: 300,
    requirement: { type: 'custom', metric: 'unique_tiles', target: 26 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'corner_explorer',
    category: 'exploration',
    title: 'Corner Explorer',
    description: 'Land on all 4 corner tiles',
    icon: '🗺️',
    reward: 100,
    requirement: { type: 'custom', metric: 'all_corners', target: 4 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'start_lover',
    category: 'exploration',
    title: 'Start Lover',
    description: 'Pass Start 50 times',
    icon: '🏁',
    reward: 200,
    requirement: { type: 'custom', metric: 'start_passes', target: 50 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'round_tripper',
    category: 'exploration',
    title: 'Round Tripper',
    description: 'Complete 10 full board loops',
    icon: '🔄',
    reward: 300,
    requirement: { type: 'custom', metric: 'board_loops', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'favorite_spot',
    category: 'exploration',
    title: 'Favorite Spot',
    description: 'Land on the same tile 20 times',
    icon: '📍',
    reward: 150,
    requirement: { type: 'custom', metric: 'same_tile_visits', target: 20 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'board_master',
    category: 'exploration',
    title: 'Board Master',
    description: 'Land on each tile at least 10 times',
    icon: '🎯',
    reward: 500,
    requirement: { type: 'custom', metric: 'all_tiles_10x', target: 1 },
    isHidden: false,
    isSecret: false,
  },

  // ========== TIME-BASED (7 achievements) ==========
  {
    id: 'comeback_kid',
    category: 'time',
    title: 'Comeback Kid',
    description: 'Play again after 30 days away',
    icon: '🎉',
    reward: 100,
    requirement: { type: 'custom', metric: 'comeback', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'daily_player',
    category: 'time',
    title: 'Daily Player',
    description: 'Play for 7 days in a row',
    icon: '⏰',
    reward: 150,
    requirement: { type: 'streak', metric: 'consecutiveDays', target: 7 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'dedicated_player',
    category: 'time',
    title: 'Dedicated Player',
    description: 'Play for 30 days in a row',
    icon: '📅',
    reward: 500,
    requirement: { type: 'streak', metric: 'consecutiveDays', target: 30 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'hardcore_player',
    category: 'time',
    title: 'Hardcore Player',
    description: 'Play for 100 days in a row',
    icon: '📅',
    reward: 2000,
    requirement: { type: 'streak', metric: 'consecutiveDays', target: 100 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'veteran',
    category: 'time',
    title: 'Veteran',
    description: 'Play for 365 days in a row',
    icon: '🏆',
    reward: 5000,
    requirement: { type: 'streak', metric: 'consecutiveDays', target: 365 },
    isHidden: false,
    isSecret: true,
  },
  {
    id: 'early_bird',
    category: 'time',
    title: 'Early Bird',
    description: 'Play before 6 AM',
    icon: '🌅',
    reward: 50,
    requirement: { type: 'custom', metric: 'early_morning', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'night_owl',
    category: 'time',
    title: 'Night Owl',
    description: 'Play after midnight',
    icon: '🦉',
    reward: 50,
    requirement: { type: 'custom', metric: 'late_night', target: 1 },
    isHidden: false,
    isSecret: false,
  },

  // ========== HIDDEN/SECRET (7 achievements) ==========
  {
    id: 'perfect_game',
    category: 'hidden',
    title: 'Perfect Game',
    description: '???',
    icon: '🏆',
    reward: 1500,
    requirement: { type: 'custom', metric: 'never_negative', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'speedrunner',
    category: 'hidden',
    title: 'Speedrunner',
    description: '???',
    icon: '⚡',
    reward: 800,
    requirement: { type: 'custom', metric: 'million_under_50_rolls', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'minimalist',
    category: 'hidden',
    title: 'Minimalist',
    description: '???',
    icon: '🎯',
    reward: 600,
    requirement: { type: 'custom', metric: 'millionaire_under_10_stocks', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'diversification_master',
    category: 'hidden',
    title: 'Diversification Master',
    description: '???',
    icon: '🌈',
    reward: 750,
    requirement: { type: 'custom', metric: 'own_50_unique_stocks', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'lucky_number_seven',
    category: 'hidden',
    title: 'Lucky Number Seven',
    description: '???',
    icon: '7️⃣',
    reward: 777,
    requirement: { type: 'custom', metric: 'exactly_7_holdings', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'zero_to_hero',
    category: 'hidden',
    title: 'Zero to Hero',
    description: '???',
    icon: '🚀',
    reward: 1000,
    requirement: { type: 'custom', metric: 'broke_to_millionaire', target: 1 },
    isHidden: true,
    isSecret: true,
  },
  {
    id: 'the_whale',
    category: 'hidden',
    title: 'The Whale',
    description: '???',
    icon: '🐋',
    reward: 2000,
    requirement: { type: 'custom', metric: 'single_stock_million', target: 1 },
    isHidden: true,
    isSecret: true,
  },

  // ========== CHALLENGES (5 achievements) ==========
  {
    id: 'thrifty_challenger',
    category: 'challenges',
    title: 'Thrifty Challenger',
    description: 'Complete your first Thrifty Path challenge',
    icon: '💎',
    reward: 75,
    requirement: { type: 'custom', metric: 'thrifty_challenges', target: 1 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'thrifty_master',
    category: 'challenges',
    title: 'Thrifty Master',
    description: 'Complete 10 Thrifty Path challenges',
    icon: '💎',
    reward: 300,
    requirement: { type: 'custom', metric: 'thrifty_challenges', target: 10 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'challenge_seeker',
    category: 'challenges',
    title: 'Challenge Seeker',
    description: 'Complete 5 daily challenges',
    icon: '🎯',
    reward: 150,
    requirement: { type: 'custom', metric: 'daily_challenges', target: 5 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'challenge_master',
    category: 'challenges',
    title: 'Challenge Master',
    description: 'Complete 25 daily challenges',
    icon: '🎯',
    reward: 500,
    requirement: { type: 'custom', metric: 'daily_challenges', target: 25 },
    isHidden: false,
    isSecret: false,
  },
  {
    id: 'hard_mode',
    category: 'challenges',
    title: 'Hard Mode',
    description: 'Complete 10 hard daily challenges',
    icon: '💪',
    reward: 750,
    requirement: { type: 'custom', metric: 'hard_challenges', target: 10 },
    isHidden: false,
    isSecret: false,
  },
]

// Helper functions
export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id)
}

export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return ACHIEVEMENTS.filter(a => a.category === category)
}

export function getVisibleAchievements(unlockedIds: string[]): Achievement[] {
  return ACHIEVEMENTS.filter(a => {
    if (a.isSecret && !unlockedIds.includes(a.id)) return false
    return true
  })
}

export function getTotalAchievementRewards(): number {
  return ACHIEVEMENTS.reduce((sum, a) => sum + a.reward, 0)
}
